spring:
  datasource:
    url: jdbc:h2:mem:produitDB
    driver-class-name: org.h2.Driver
    username: user
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true